apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kekboard-token-secret
  namespace: kekboard
spec:
  encryptedData:
    BOT_TOKEN: AgAZhiW43ygvtXS64pVQfC/8DSH49FfP6YdCKRW5POrfkKv1yIGwMIRSC9WMmjRtLqkmE4pdW4nuKrtdHSj36gbOOQxkfwW2Ns+ac0k+EIMoZXEvW0nHAjYWHnx49WX4bYALE163MtSxaIqxmwfjF6Cb9h17622Ol0W2Snlb3Q5RQbb5tFKX0N86XceZhxhSeN/JXtl7W1Hunrgrfu+EpacKfDPzsUCzXixKp5hgWM1iIPty+w79z3o89JqhM30E+K5fxlEYltXwyXoZG1c5AOK3/tcpKdLiY2K611+q5gABmOgwFADzsEyTv+nj/WD/VRe+hH2EpMEY/R2dspVMRHud3olcUnX9e8VIVbgqvb23oiQPjxCpj08Yey3Lm8MP+AYWy8RYASnayp5kWW96tojBXkNTA/E2+QNv8wxIsRcaltd7jvOXrRVxIR1apo5XiUvc0XdrTie9U8UUcX+yfWuJ1D98bgKX/wbn1EQc6ddjq4ekeb16w+3n9hNiIWryesxy6sO9HO3zC5xg8odRjX8SAB9xWPgcpp64TneNJP308VD4QVZkwdwWXds9UAU6+XefifUZfKlJ7o0M3Icq8EasEkVn+xazfvYxHsyAcUJ/99s6GwzVj2t4Nj5bcqKXV+FNyJNFZZXI/shU+Ug72gA91Pbg5cknANh/cL0BBuctITG0jibnfki2Q1Ok7iMdjqDrzOk7AY7odVBHzOV7e/K633qWmnKj8nuvYfFTv3T1d3bEuYo3r3O48PA1plYFkE1uDIuFXFfO/FcJXA==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: kekboard-token-secret
      namespace: kekboard

