apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./namespace.yaml
- ./kekboard.yaml
- ./kekboard-token-secret-sealed.json
- ./dashboard.yaml
- ./letsencrypt-issuer.yaml
- ./traefik-middleware.yaml
namespace: kekboard
