apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: kekboard
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: invakid404@riseup.net
    privateKeySecretRef:
      name: letsencrypt
    solvers:
    - http01:
        ingress:
          class: traefik
